### ISSUE TITLE
Cannot Harvest Deposit

### ISSUE THREAD

**Issue by Longtianmu** [exaV/screeps-kotlin-types#76]
Actually, it's difficult to figure out that why Harvestable is not in Identifible.
Besides,there is no way to harvest deposit

**Comment by exaV** [comment]
Here's an example of how to harvest from a d(from the starter project):
```
        val creep = // some creen
        val sources = creep.room.find(FIND_SOURCES)
        if (creep.harvest(sources[0]) == ERR_NOT_IN_RANGE) {
            creep.moveTo(sources[0].pos)
        }
```

We try to keep things simple and to avoid mixing the interfaces too much. That's why for example `Owned` is not `Identifieable` either. In my playthrough it has not been a problem. I keep a list of `Mineral` not a list of `Harvestable` in my code and I use `Game.getObjectById<Mineral>` to load them by id. That being said, if it you can make a good case for why `Harvestable` should be `Identifieable` then I am not opposed to adding it.

**Comment by Longtianmu** [comment]
If I want to use Task or some a more powerful way,
I will stored Source/Deposit/Mineral's ID in memory and Game.getObjectByID<STH>(id)
And here is the problem-I can't harvest a Identifable so I need to cast it to Source/Deposit/Mineral like
```
  val target = Game.getObjectById<Identifiable>(targetID).unsafeCast<Source/Mineral/Deposits>(targetID)
```
However the step can be used for Anything that is harvestable so I can't cast it to any specific type
If I can use Harvestale instead,the problem will be much easier like that:
```
    val target = Game.getObjectById<Harvestable>(targetID) 

    creep.harvest(target)
```

**Comment by Longtianmu** [comment]
A off-topic problem:
How can I use IR Backend when use this project?
It will always throw an error like that
![image](https://user-images.githubusercontent.com/60567448/184478782-73173c67-c836-4b58-9ba4-4d17c733a8b9.png)

**Comment by exaV** [comment]
fixed with https://github.com/exaV/screeps-kotlin-types/commit/ad554d7a65fed92d2d5bb0ba1ad72e41b146b5ac
